### ISSUE TITLE
Not getting location when asking a new one

### ISSUE THREAD

**Issue by facundomedica** [delight-im/Android-SimpleLocation#12]
If I use this constructor:

``` java
public SimpleLocation(final Context context, final boolean requireFine, final boolean passive, final long interval, final boolean requireNewLocation) {...}
```

Passing true to requireNewLocation I can't get a location and onLocationChanged is never called.

But using works perfectly:

``` java
public SimpleLocation(final Context context, final boolean requireFine, final boolean passive, final long interval) {
    this(context, requireFine, passive, interval, false);
}
```

EDIT:
Well, not that perfectly in a Samsung Galaxy S4 mini

EDIT 2:
I realized that it's reaching the catch inside this function, but I can't check the error (Maybe I'll have to run the source):

``` java
    private Location getCachedPosition() {
        if (mCachedPosition != null) {
            return mCachedPosition;
        }
        else {
            try {
                return mLocationManager.getLastKnownLocation(getProviderName());
            }
            catch (Exception e) {
                return null;
            }
        }
    }
```

Maybe a bug?
Thanks!

**Comment by ocram** [comment]
> Passing true to requireNewLocation I can't get a location and onLocationChanged is never called.

Setting `requireNewLocation` to `true` prevents you from being able to use any cached locations. Thus a new location must indeed be detected for this configuration. This may take some time. But no matter how many seconds it takes, there really should be some result.

Are you sure you've set up your callback correctly and logged something in the `onLocationChanged` method of that callback?

What about your device configuration? Is network location or GPS location set up correctly? Does it work with other apps?

``` java
public SimpleLocation(final Context context, final boolean requireFine, final boolean passive, final long interval) {
    this(context, requireFine, passive, interval, false);
}
```

Can you show how you _call_ that method instead of how it's _defined_ by this library? That would be more helpful (in this and the previous case). Thanks!

>  I realized that it's reaching the catch inside this function, but I can't check the error (Maybe I'll have to run the source)

That's definitely some helpful information. Thank you!
- Are you sure you've added the correct permissions to your app? To exclude this possible issue during development, consider adding both permissions (see README).
- It really depends on the way you _call_ that constructor. Make sure _not_ to enable passive mode while using a network/coarse location. Passive mode is only available for GPS/fine location.
- You can checkout the code from this project and run the included sample application from Android Studio. This way, you can test all configurations that you're interested in while being able to change the library's code (in the included module) and adding log statements. Unfortunately, we can't debug that piece for you because we don't have the issues that you have.
