### ISSUE TITLE
It giving me error in onResume()  " Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission." though i have given permission in manifest file

### ISSUE THREAD

**Issue by sagarchaure21** [delight-im/Android-SimpleLocation#14]

**Comment by ocram** [comment]
This error message is pretty specific: The required permission is not there. It's really as simple as that.

First check your manifest file and confirm that you've added the permission correctly.

Apart from that, it could only be caused by the runtime permissions which have been introduced in Android 6.0. So if your `android:targetSdkVersion` is set to `23` or above, you will have to implement the runtime permissions. If you don't want to do that, you have to decrease the target version.
